spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/root
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

server:
  port: 8080